set_location_assignment PIN_AM29 -to oDVI_TX_DATA[0]
set_location_assignment PIN_AL29 -to oDVI_TX_DATA[1]
set_location_assignment PIN_AH30 -to oDVI_TX_DATA[2]
set_location_assignment PIN_AJ31 -to oDVI_TX_DATA[3]
set_location_assignment PIN_AL31 -to oDVI_TX_DATA[4]
set_location_assignment PIN_AK31 -to oDVI_TX_DATA[5]
set_location_assignment PIN_AH27 -to oDVI_TX_DATA[6]
set_location_assignment PIN_AG27 -to oDVI_TX_DATA[7]
set_location_assignment PIN_AL32 -to oDVI_TX_DATA[8]
set_location_assignment PIN_AK32 -to oDVI_TX_DATA[9]
set_location_assignment PIN_AD31 -to oDVI_TX_DATA[10]
set_location_assignment PIN_AD30 -to oDVI_TX_DATA[11]
set_location_assignment PIN_AC28 -to oDVI_TX_DATA[12]
set_location_assignment PIN_AC29 -to oDVI_TX_DATA[13]
set_location_assignment PIN_AJ29 -to oDVI_TX_DATA[14]
set_location_assignment PIN_AK29 -to oDVI_TX_DATA[15]
set_location_assignment PIN_AG28 -to oDVI_TX_DATA[16]
set_location_assignment PIN_AP34 -to oDVI_TX_DATA[17]
set_location_assignment PIN_AP32 -to oDVI_TX_DATA[18]
set_location_assignment PIN_AR32 -to oDVI_TX_DATA[19]
set_location_assignment PIN_AR31 -to oDVI_TX_DATA[20]
set_location_assignment PIN_AT30 -to oDVI_TX_DATA[21]
set_location_assignment PIN_AT33 -to oDVI_TX_DATA[22]
set_location_assignment PIN_AU33 -to oDVI_TX_DATA[23]

set_location_assignment PIN_AG34 -to oDVI_TX_CLK
set_location_assignment PIN_AV34 -to oDVI_TX_HS
set_location_assignment PIN_AT32 -to oDVI_TX_VS
set_location_assignment PIN_AK30 -to oDVI_TX_DE
set_location_assignment PIN_AP33 -to oDVI_TX_ISEL
set_location_assignment PIN_AR34 -to oDVI_TX_SCL
set_location_assignment PIN_AP35 -to oDVI_TX_HTPLG
set_location_assignment PIN_AT34 -to oDVI_TX_SDA
set_location_assignment PIN_AR35 -to oDVI_TX_PD_n

set_location_assignment PIN_AC35 -to iCLK
set_location_assignment PIN_V34 -to iRST_N